applications/actividad/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name='actividades_app'
urlpatterns = [
    path('',views.InicioView.as_view(),name='inicio'),
    path('crear-actividad/', views.CrearActividad.as_view(),name='add-actividad'),
    path('ver-actividades/',views.ActividadListView.as_view(),name='all-activities'),
    path('actividades-categoria/<descripcion>',views.ActividadByCategoria.as_view(),name='actividades-categoria'),
    path('detalle-actividad/<pk>',views.ActividadDetailView.as_view(),name='activity-detail'),
    path('editar-actividad/<pk>',views.ActividadUpdateView.as_view(),name='update-activity'),
    path('pdf-activity/',views.ActividadPDF.as_view(),name='generate-pdf'),
    path('eliminar-actividad/<int:id_actividad>',views.eliminar_actividad,name='eliminar_actividad'),
    path('login',views.login_page ,name='login'),
    path('logout',views.logout_user,name='logout')
  
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

imjuve_crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluir los url's de las aplicaciones
    path('', include('applications.actividad.urls')),
] 

applications/actividad/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    """Model definition for Categoria."""
    descripcion = models.CharField('Descripcion',max_length=500)

    class Meta:
        """Meta definition for Categoria."""

        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):

        return self.descripcion

class Actividad(models.Model):
    """Model definition for Actividad."""

    nombre = models.CharField('Nombre',max_length=50)
    fecha = models.DateField('Fecha')
    participantes = models.IntegerField('Participantes',max_length=None)
    objetivo = models.CharField('Objetivo',max_length=500)
    descripcion = models.CharField('Descripcion',max_length=2000)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='actividad',blank=True,null=True)
    class Meta:
        """Meta definition for Actividad."""

        verbose_name = 'Actividad'
        verbose_name_plural = 'Actividades'

    def __str__(self):
        return self.nombre

applications/actividad/forms.py
from django import forms
from .models import Actividad


class ActividadForm(forms.ModelForm):
    """Form definition for Actividad."""

    class Meta:
        """Meta definition for Actividadform."""

        model = Actividad
        fields = ('nombre',
        'fecha',
        'participantes',
        'objetivo',
        'descripcion',
        'categoria',
        'imagen')

        widgets={
            'nombre':forms.TextInput(
                attrs={
                    'placeholder':'Nombre de la actividad',
                    'id':'nombre_actividad'
                }
            ),
            'fecha':forms.DateInput(
                attrs={
                    'type':'date'
                }
            ),
            'participantes':forms.NumberInput(
                attrs={
                    'placeholder':'N° participantes',
                    'id':'participantes_actividad'
                }
            ),
            'objetivo':forms.Textarea(
                attrs={
                    'placeholder':'Objetivo de la actividad',
                    'cols':'30',
                    'rows':'20',
                    'id':'objetivo_actividad'
                }
            ),
            'categoria':forms.Select(
                attrs={
                    'id':'categoria_actividad'
                }
            ),
            'descripcion':forms.Textarea(
                attrs={
                    'placeholder':'Descripcion de la actividad',
                    'cols':'30',
                    'rows':'20',
                    'id':'descripcion_actividad'
                    
                }
            ),
            'imagen':forms.ClearableFileInput(
                
            ),
               
        }

applications/actividad/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView, View
from .models import Actividad, Categoria
from django.http import HttpResponse
from django.urls import reverse_lazy
from .utils import render_to_pdf
from .forms import ActividadForm

from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.views.decorators.csrf import csrf_protect
# Create your views here.


class InicioView(TemplateView):
    template_name = "index.html"


class Prueba(TemplateView):
    template_name = "insertar.html"


class CrearActividad(CreateView):
    template_name = 'registrarActividad.html'
    model = Actividad
    form_class = ActividadForm

    success_url = reverse_lazy('actividades_app:add-actividad')

    @csrf_protect
    def form_valid(self, form):
        actividad = form.save()
        actividad.save()
        return super(CrearActividad, self).form_valid(form)
    success_url = reverse_lazy('actividades_app:all-activities')

class ActividadListView(ListView):
    model = Actividad
    template_name = "actividades_list.html"

    def get_queryset(self):
        palabraClave = self.request.GET.get('kword','')

        #buscar por nombre de actividad
        lista = Actividad.objects.filter(
            nombre__icontains=palabraClave 
            
        )

        #buscar actividad por fecha
        if len(lista)<1:
            lista = Actividad.objects.filter(
            fecha__icontains=palabraClave 
            
        )

        return lista


class ActividadByCategoria(ListView):
    template_name = 'actividad_categoria.html'

    def get_queryset(self):
        categoria = self.kwargs['descripcion']
        lista = Actividad.objects.filter(
            categoria__descripcion=categoria
        )
        return lista




class ActividadDetailView(DetailView):
    model = Actividad
    template_name = "detail_activity.html"

    def get_context_data(self, **kwargs):
        context = super(ActividadDetailView, self).get_context_data(**kwargs)
        return context


class ActividadUpdateView(UpdateView):
    template_name = "update.html"
    model = Actividad
    form_class = ActividadForm
    success_url = reverse_lazy('actividades_app:all-activities')


class ActividadPDF(View):
    def get(self, request, *args, **kwargs):
        actividades = Actividad.objects.all()
        data = {
            'actividades': actividades
        }
        pdf = render_to_pdf('detail_activity.html', data)
        return HttpResponse(pdf, content_type='application/pdf')


def eliminar_actividad(self, id_actividad):
    actividad = Actividad.objects.get(id=id_actividad)
    actividad.delete()
    return redirect(reverse_lazy('actividades_app:all-activities'))


#Inicios de sesion
@csrf_protect
def login_page(request):

    if request.method=='POST': #Nos llega informacion del formulario
        username=request.POST.get('username')
        password=request.POST.get('password')


        user=authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            return redirect(reverse_lazy('actividades_app:inicio'))
        else:
            messages.warning(request,'No te has identificado correctamente!!')

    return render(request,'login.html',{
        'title':'Identificate'
    }
    )

def logout_user(request):
    logout(request)
    return redirect(reverse_lazy('actividades_app:inicio'))

templates/actividad_categoria.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Lista de actividades
{% endblock title %}
    

{% block content %}
    {% include 'header.html' %}
    <main class="main contenedor">
        <h2>Actividades</h2>
      <section class="actividades contenedor">
        
       
       {% if object_list %}
       {% for actividad in object_list  %}
       <div class="actividad">
           <img src="{{actividad.imagen.url}}" class="img-actividad" />
           <div class="info-actividad">
             <h3 class="nombre-actividad"> <a href="{% url 'actividades_app:activity-detail' actividad.id %}">{{actividad.nombre}}</a> </h3>
             <p class="objetivo-actividad">
               {{actividad.objetivo}}
             </p>
             <div class="detalle-actividad">
               <span>{{actividad.categoria}}</span>
               <span>{{actividad.fecha}}</span>
             </div>
           </div>
           <div class="botones-actividad">
             <button class="btn-editar"> <a href="{% url 'actividades_app:update-activity' actividad.id %}">Editar</a> </button>
             <button class="btn-eliminar"><a href="{% url 'actividades_app:eliminar_actividad' actividad.id %}">Eliminar</a></button>
           </div>
         </div>
       {% endfor %}
       {% else %}
        <h3 style="text-align:center;">No hay actividades por mostrar</h3>
        <img src="{% static 'img/vacio.jpg' %}" class="img-actividad"  style="height:500px ;"/>
       {% endif %}
        
            
        <!---->
        
          
      </section>
    </main>
    {% include 'footer.html' %}
{% endblock content %}
    

templates/actividades_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Lista de actividades
{% endblock title %}
    

{% block content %}
    {% include 'headerSearch.html' %} 

    <main class="main contenedor">
        <h2>Actividades</h2>
      <section class="actividades contenedor">
        
        
        {% if  object_list%}
          {% for actividad in object_list  %}
          <div class="actividad">
            
            
            {% if actividad.imagen %}
            <img src="{{actividad.imagen.url}}" class="img-actividad" />
            {% else %}
            <img src="{% static 'img/beneficios.png' %}" class="img-actividad" />
            {% endif %}
              
              
              <div class="info-actividad">
                <h3 class="nombre-actividad"> <a href="{% url 'actividades_app:activity-detail' actividad.id %}">{{actividad.nombre  | capfirst}}</a> </h3>
                <p class="objetivo-actividad">
                  {{actividad.objetivo}}
                </p>
                <div class="detalle-actividad">
                  <span>{{actividad.categoria  | capfirst }}</span>
                  <span>{{actividad.fecha}}</span>
                </div>
              </div>
              <div class="botones-actividad">
                <button class="btn-editar"> <a href="{% url 'actividades_app:update-activity' actividad.id %}">Editar</a> </button>
                <button class="btn-eliminar"><a href="{% url 'actividades_app:eliminar_actividad' actividad.id %}">Eliminar</a></button>
              </div>
            </div>
          {% endfor %}
        {% else %}
        <h3 style="text-align:center;">No hay actividades por mostrar</h3>
        <img src="{% static 'img/vacio.jpg' %}" class="img-actividad"  style="height:500px ;"/>
        {% endif %}
          
            
        <!---->
        
          
      </section>
    </main>
    {% include 'footer.html' %}
{% endblock content %}
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    <title>
    {% block title %}
      ADMINPYT
    {% endblock title %}
      </title>
  </head>
  <body>
   
   {% block content %}
 
   {% endblock content %}
     
    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

templates/detail_activity.html
{% extends 'base.html' %} 
{% block title %} Registrar actividad {% endblock title %}
{% block content %}
{% load static %}
{% include 'header.html' %}
<main class="main contenedor">
    <section class="header-detail-activity">
      <h2 style="text-transform:uppercase ;">{{actividad.nombre}}</h2>
      <a href="{% url 'actividades_app:generate-pdf' %}" target="_blank" class="btn-eliminar">PDF</a>
    </section>
    <section class="data-detail-activty">
      <span>Participantes: {{actividad.participantes}} </span>
      <span>Fecha:{{actividad.fecha}} </span>
    </section>
    <section class="objetivo-detail-activity">
      <h3>Objetivo:</h3>
      <p>
       {{actividad.objetivo}}
      </p>
    </section>
    <br>
    <section class="descrpcion-detail-activity">
        <h3>Descripcion:</h3>
      <p>
        {{actividad.descripcion}}
      </p>
    </section>

    <section class="evidencias-detail-activity">
      <section class="imagenes-evidencias">

                
           
           {% if actividad.imagen %}
           <img src="{{actividad.imagen.url }}" class="img-detail-activity" />
           {% else %}
           <img src="{% static 'img/beneficios.png' %}" class="img-detail-activity" />
           {% endif %}

      </section>
    </section>
  </main>

{% include 'footer.html' %}

{% endblock content %}

templates/footer.html
<footer class="footer">
    <section class="link">Intituto Cultural y social</section>
    <section class="logo-footer">ADMINPYT</section>
  </footer>

templates/header.html
<header class="hero">
    <div class="logo">
      <a href="{% url 'actividades_app:inicio' %}">
        <h1>ADMINPYT</h1>
      </a>
    </div>
  </header>
  <nav class="menu contenedor">
    <ul>
      <li>
        <a href="{% url 'actividades_app:add-actividad' %}">Insertar</a>
      </li>
      <li>
        <a href="{% url 'actividades_app:all-activities' %}">Ver</a>
      </li>
      <li>
        <a href="#">Categorias</a>
        <ul>
          
          {% for categoria in categorias %}
          <li><a href="{% url 'actividades_app:actividades-categoria' categoria.descripcion%}">{{categoria.descripcion  | capfirst}}</a></li>
          {% endfor %}
        </ul>
      </li>
      <li>
        <a href=" {% url 'actividades_app:logout' %}">Cerrar Sesion</a>
      </li>
    </ul>
 
  </nav>

templates/headerSearch.html
<header class="hero">
    <div class="logo">
      <a href="{% url 'actividades_app:inicio' %}">
        <h1>ADMINPYT</h1>
      </a>
    </div>
  </header>
  <nav class="menu contenedor">
    <ul>
      <li>
        <a href="{% url 'actividades_app:add-actividad' %}">Insertar</a>
      </li>
      <li>
        <a href="{% url 'actividades_app:all-activities' %}">Ver</a>
      </li>
      <li>
        <a href="#">Categorias</a>
        <ul>
          
          {% for categoria in categorias %}
          <li><a href="{% url 'actividades_app:actividades-categoria' categoria.descripcion%}">{{categoria.descripcion  | capfirst}}</a></li>
          {% endfor %}
        </ul>
      </li>
      <li>
        <a href=" {% url 'actividades_app:logout' %}">Cerrar Sesion</a>
      </li>
    </ul>
    <section class="buscador">
      <form class="buscador-actividades"  method="get">
        {% csrf_token %}
        <input type="text" placeholder="Buscar actividad" id="kword" name="kword" />
        <input type="submit" value="Buscar">
       </form>
  
    </section>
  </nav>

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    
   


{% if user.email %}
{% include 'header.html' %}
<main class="main contenedor">
  <section class="img-principal contenedor">
    <img src="{% static 'img/beneficios.png' %}" alt="imagen" />
  </section>

  <article class="article contenedor">
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate
      distinctio a quaerat similique at sapiente saepe quam suscipit fuga,
      reiciendis maxime sit molestiae, ipsam quisquam aliquam libero ex
      officia fugiat! Lorem ipsum dolor sit amet consectetur adipisicing
      elit. Fugit assumenda incidunt libero, expedita necessitatibus atque
      tempora nemo eaque unde cumque cum reprehenderit! Aut numquam ducimus
      omnis, voluptatibus eveniet velit natus. Lorem ipsum dolor sit amet
      consectetur adipisicing elit. Molestiae ea ad atque! Provident,
      necessitatibus. Unde sint deserunt, molestiae fuga provident quis. Eum
      porro optio, ipsam ex labore assumenda provident possimus!
    </p>

    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias,
      reiciendis natus aliquam tempore eum corrupti sit architecto eius
      nulla incidunt fuga, reprehenderit illum doloribus odit, iusto neque?
      Perspiciatis, id nisi?
    </p>
  </article>
</main>
{% else %}
<header class="hero">
  <div class="logo">
    <a href="{% url 'actividades_app:inicio' %}">
      <h1>ADMINPYT</h1>
    </a>
  </div>
</header>
  <main class="main contenedor">

    <h2>Idetificate </h2>

    <section class="img-principal contenedor">
      <img src="{% static 'img/beneficios.png' %}" alt="imagen" />
    </section>
  
    <section class="botones">
      <a href=" {% url 'actividades_app:login' %}" class="btn-guardar btn-inicar-sesion">Iniciar Sesion</a>
    </section>

  </main>

{% endif %}

  
    
    {% include 'footer.html' %}
{% endblock content %}
    

templates/lista.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Lista de actividades
{% endblock title %}
    

{% block content %}
    {% include 'header.html' %}
    <main class="main contenedor">
        <h2>Actividades</h2>
      <section class="actividades contenedor">
        <a href="{% url 'actividades_app:generate-pdf' %}" target="_blank" class="btn-eliminar">PDF</a>
        {% for actividad in actividades  %}
        <div class="actividad">
            <img src="{% static 'img/beneficios.png' %}" class="img-actividad" />
            <div class="info-actividad">
              <h3 class="nombre-actividad"> <a href="{% url 'actividades_app:activity-detail' actividad.id %}">{{actividad.nombre}}</a> </h3>
              <p class="objetivo-actividad">
                {{actividad.objetivo}}
              </p>
              <div class="detalle-actividad">
                <span>{{actividad.categoria}}</span>
                <span>{{actividad.fecha}}</span>
              </div>
            </div>
            <div class="botones-actividad">
               <a class="btn-editar" href="{% url 'actividades_app:update-activity' actividad.id %}">Editar</a>
              <button class="btn-eliminar">Eliminar</button>
            </div>
          </div>
        {% endfor %}
            
        <!---->
        
          
      </section>
    </main>
    {% include 'footer.html' %}
{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<header class="hero">
    <div class="logo">
      <a href="{% url 'actividades_app:inicio' %}">
        <h1>ADMINPYT</h1>
      </a>
    </div>
  </header>

  <main class="main contenedor">
    <section class="formulario-login">
        <form action="" method="post">
            {% csrf_token %}
            <h3>LOGIN</h3>
            <label for="user">Usuario:</label>
            <input type="text" name="username" id="user" />
            <label for="password">Contraseña:</label>
            <input type="password" name="password" id="password" />
            <input type="submit" value="Entrar" />
        
          </form>
    </section>
  </main>
   
  {% include 'footer.html' %}

{% endblock content %}
    

templates/registrarActividad.html
{% extends 'base.html' %} 
{% block title %} Registrar actividad {% endblock title %}
{% block content %}

{% include 'header.html' %}
<main class="main contenedor">
    <h2>Agregar Actividad</h2>

    <div id="error" class="errorDiv"></div>
   <section class="contenedor-formulario">
    <form class="formulario contenedor" method="post" enctype="multipart/form-data">{% csrf_token %}
       <label for="nombre">Nombre:</label>
        {{form.nombre}}

        <label for="fecha">Fecha:</label>
        {{form.fecha}}

        <label for="participantes">Participantes:</label>
        {{form.participantes}}

        <label for="objetivo">Objetivo:</label>
        {{form.objetivo}}

        <label for="categoria">Categoria:</label>
        {{form.categoria}}

        <label for="imagen">Imagen:</label>
        {{form.imagen}}

        <label for="descripcion">Descripcion:</label>
        {{form.descripcion}}

       
        <input type="submit" id="btn-guardar-actividad" class="btn-guardar" value="Guardar">
    </form>
   </section>

</main>

{% include 'footer.html' %}

{% endblock content %}

templates/update.html
{% extends 'base.html' %} 
{% block title %} Registrar actividad {% endblock title %}
{% block content %}

{% include 'header.html' %}
<main class="main contenedor">
    <h2>Editar Actividad</h2>

    <div id="error" class="errorDiv"></div>
   <section class="contenedor-formulario">
    <form class="formulario contenedor" method="post" enctype="multipart/form-data">{% csrf_token %}
       <label for="nombre">Nombre:</label>
        {{form.nombre}}

        <label for="fecha">Fecha:</label>
        {{form.fecha}}

        <label for="participantes">Participantes:</label>
        {{form.participantes}}

        <label for="objetivo">Objetivo:</label>
        {{form.objetivo}}

        <label for="categoria">Categoria:</label>
        {{form.categoria}} 

        <label for="imagen">Imagen:</label>
        {{form.imagen}} 

        <label for="descripcion">Descripcion:</label>
        {{form.descripcion}}

       
        <input type="submit" id="btn-guardar-actividad" class="btn-guardar" value="Actualizar">
    </form>
   </section>

</main>

{% include 'footer.html' %}

{% endblock content %}